# Generated by Django 4.1.7 on 2024-06-15 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmAppAlgorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('algorithm_name', models.CharField(max_length=100)),
                ('indicator_id', models.CharField(max_length=100, null=True)),
                ('cpu_count', models.CharField(max_length=100, null=True)),
                ('mem_limit', models.CharField(max_length=100, null=True)),
                ('container_created', models.BooleanField()),
                ('container_status', models.BooleanField(null=True)),
                ('container_id', models.CharField(max_length=100, null=True)),
                ('container_port', models.CharField(max_length=100, null=True)),
                ('container_ip', models.CharField(max_length=100, null=True)),
                ('dataset_path', models.CharField(max_length=300, null=True)),
                ('is_split', models.BooleanField()),
                ('run_command', models.CharField(max_length=100, null=True)),
                ('train_command', models.CharField(max_length=100, null=True)),
                ('test_command', models.CharField(max_length=100, null=True)),
                ('dataset_type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'algorithm_app_algorithm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmAppAlgorithmType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'algorithm_app_algorithmtype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmAppTasktemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('indicator_id', models.CharField(max_length=100)),
                ('create_person', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='algorithm_app.algorithmappalgorithm')),
            ],
            options={
                'db_table': 'algorithm_app_tasktemplate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlgorithmAppTaskexecute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset_range', models.CharField(blank=True, max_length=100, null=True)),
                ('execute_type', models.IntegerField()),
                ('execute_result', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('create_person', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField()),
                ('execute_person', models.CharField(blank=True, max_length=100, null=True)),
                ('execute_status', models.CharField(blank=True, max_length=100, null=True)),
                ('pid', models.CharField(blank=True, max_length=100, null=True)),
                ('container_pid', models.CharField(blank=True, max_length=100, null=True)),
                ('train_or_test', models.CharField(blank=True, max_length=100, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='algorithm_app.algorithmapptasktemplate')),
            ],
            options={
                'db_table': 'algorithm_app_taskexecute',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='algorithmappalgorithm',
            name='algorithm_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='algorithm_app.algorithmappalgorithmtype'),
        ),
    ]
