experiment_dir: 'experiment'
origin_metric_dir: 'origin_data/metric'
origin_log_dir: 'origin_data/log'
origin_trace_dir: 'origin_data/trace'
origin_groundtruth_dir: 'origin_data/groundtruth'

# mysql
host: 223.193.36.169
user: root
password: '123456'
port: 4000
database: platform