processed_data:
  nodes: 'cartservice-0 cartservice-1 cartservice-2 checkoutservice-0 checkoutservice-1 checkoutservice-2  currencyservice-0 currencyservice-1 currencyservice-2 emailservice-0 emailservice-1 emailservice-2 frontend-0 frontend-1 frontend-2 paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 recommendationservice-0 recommendationservice-1 recommendationservice-2 shippingservice-0 shippingservice-1 shippingservice-2 redis-cart-0'
  process_dir: 'processed_data'
  metric_dir: 'processed_data/metric'
  log_dir: 'processed_data/log'
  trace_dir: 'processed_data/trace'
  metric_path: 'processed_data/metric/processed_metric.npy'
  trace_path: 'processed_data/trace/processed_trace.npy'
  log_path: 'processed_data/log/processed_log.npy'
  save_path: 'processed_data/stratification_texts.pkl'
  run_table_path: 'run_table.csv'

fasttext:
  supervised: True
  dataset: '22aiops'
  nodes: 'cartservice-0 cartservice-1 cartservice-2 checkoutservice-0 checkoutservice-1 checkoutservice-2  currencyservice-0 currencyservice-1 currencyservice-2 emailservice-0 emailservice-1 emailservice-2 frontend-0 frontend-1 frontend-2 paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 recommendationservice-0 recommendationservice-1 recommendationservice-2 shippingservice-0 shippingservice-1 shippingservice-2 redis-cart-0'
  text_path: 'processed_data/stratification_texts.pkl'
  fasttext_dir: 'fasttext'
  temp_dir: 'fasttext/temp'
  train_path: 'fasttext/temp/train.txt'
  test_path: 'fasttext/temp/test.txt'
  train_da_path: 'fasttext/temp/train_da.txt'
  save_path: 'fasttext/event_embedding.pkl'
  vector_dim: 100
  sample_count: 1000
  edit_count: 1
  da_method: 'w2v'
  minCount: 1
  epoch: 5
  seed: 2
  model_save_dir: 'fasttext'
  model_save_path: 'fasttext/model.bin'

sentence_embedding:
  K_S: 10
  train_path: 'fasttext/temp/train.txt'
  test_path: 'fasttext/temp/test.txt'
  source_path: 'fasttext/event_embedding.pkl'
  save_dir: 'sentence_embedding'
  save_path: 'sentence_embedding/sentence_embedding.pkl'

he_dgl:
  nodes: 'cartservice-0 cartservice-1 cartservice-2 checkoutservice-0 checkoutservice-1 checkoutservice-2  currencyservice-0 currencyservice-1 currencyservice-2 emailservice-0 emailservice-1 emailservice-2 frontend-0 frontend-1 frontend-2 paymentservice-0 paymentservice-1 paymentservice-2 productcatalogservice-0 productcatalogservice-1 productcatalogservice-2 recommendationservice-0 recommendationservice-1 recommendationservice-2 shippingservice-0 shippingservice-1 shippingservice-2 redis-cart-0'
  failure_type: 'loss delay memory pod-failure cpu'
  service: 'cartservice checkoutservice currencyservice emailservice frontend paymentservice productcatalogservice recommendationservice redis shippingservice'
  heterogeneous: False
  dataset: '22aiops'
  data_dir: ''
  save_dir: 'dgl/stratification_10'
  Xs: 'sentence_embedding/sentence_embedding.pkl'
  run_table_path: 'run_table.csv'
  aug: False
  aug_size: 0
  TOPK_SA: 10
  epoch: 6000 
  batch_size: 1000 
  win_size: 10
  win_threshold: 0.0001
  lr: 0.001
  weight_decay: 0.0001
  seed: 2
  text_path: 'processed_data/stratification_texts.pkl'
  model_dir: 'dgl/stratification_10'
  service_model_path: 'dgl/stratification_10/service_model.pt'
  failure_type_model_path: 'dgl/stratification_10/failure_type_model.pt'
  tuple_path: 'dgl/tuple.csv'